[dataset]
dataset="cifra"
batch_size=256
path="data/cifra_10/cifar10.npz"
[model]
model="CNN"
in_channels=3
base_channels=64
kernel_size=[3,3]
num_classes=10
img_size=[32,32]
[train]
epoches=20
learning_rate=1e-5
loss_function="softmax_cross_entropy_with_integer_labels"