[dataset]
dataset="mnist"
batch_size=256
path="data/mnist/mnist.npz"
[model]
model="VIT"
num_classes=10
in_channels=1
img_size=28
patch_size=4
num_layers=6
num_heads=8
mlp_dim=512
hidden_size=256
dropout_rate=0.1
[train]
epoches=20
learning_rate=0.001
loss_function="softmax_cross_entropy_with_integer_labels"